name: SubServers-Client-Bukkit
main: net.ME1312.SubServers.Client.Bukkit.SubPlugin
version: "2.17a"
authors: ["ME1312"]
softdepend: [TitleManager, PlaceholderAPI]
website: "https://github.com/ME1312/SubServers-2"
#commands:
#  subservers:
#    description: "The SubServers Command"
#    usage: "/subservers is currently unavailable"
#  subserver:
#    description: "The SubServers Command"
#    usage: "/subserver is currently unavailable"
#  sub:
#    description: "The SubServers Command"
#    usage: "/sub is currently unavailable"
permissions:
  subservers.*:
    description: "Access everything in SubServers.Client"
    default: op
    children:
      subservers.interface:
        description: "Access to the SubServers Interface"
        default: op
      subservers.command:
        description: "Access to the SubServers Command"
        default: op
      subservers.teleport:
        description: "Access to SubServers' Teleport Command"
        default: op
      subservers.teleport-others:
        description: "Access to Teleport other players using the Teleport Command"
        default: op
      subservers.host.*:
        description: "Access to all Host Actions on all Hosts"
        default: op
        children:
          subservers.host.*.*:
            description: "Access to all Host Actions on all Hosts"
            default: op
            children:
              subservers.host.*.create:
                description: "Access to Create a Subserver on all Hosts"
                default: op
      subservers.subserver.*:
        description: "Access to all Subserver Actions on all Subservers"
        default: op
        children:
          subservers.subserver.*.*:
            description: "Access to all Subserver Actions on all Subservers"
            default: op
            children:
              subservers.subserver.*.start:
                description: "Access to Start all Subservers"
                default: op
              subservers.subserver.*.stop:
                description: "Access to Stop all Subservers"
                default: op
              subservers.subserver.*.terminate:
                description: "Access to Terminate all Subservers"
                default: op
              subservers.subserver.*.command:
                description: "Access to Send Commands to all Subservers"
                default: op
              subservers.subserver.*.update:
                description: "Access to Update all Subservers"
                default: op